$primary = rgb({{colors.primary.default.hex_stripped}})
$secondary = rgb({{colors.secondary.default.hex_stripped}})
$background = rgb({{colors.surface.default.hex_stripped}})
$red = rgb({{colors.gruv_red.default.hex_stripped}})
$green = rgb({{colors.gruv_green.default.hex_stripped}})
$yellow = rgb({{colors.gruv_yellow.default.hex_stripped}})
$blue = rgb({{colors.gruv_dark_blue.default.hex_stripped}})
$orange = rgb({{colors.gruv_orange.default.hex_stripped}})
$purple = rgb({{colors.gruv_purple.default.hex_stripped}})
$aqua = rgb({{colors.gruv_aqua.default.hex_stripped}})
