force_keyboard_focus = false
close_when_open = true
click_to_close = true
as_window = false
single_click_activation = true
selection_wrap = false
global_argument_delimiter = "#"
exact_search_prefix = "'"
theme = "default"
disable_mouse = false
debug = false
page_jump_items = 10
hide_quick_activation = true
hide_action_hints = true
hide_action_hints_dmenu = true
hide_return_action = false
resume_last_query = false
actions_as_menu = false
autoplay_videos = false

[shell]
exclusive_zone = -1
layer = "overlay"
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[columns]
"symbols" = 3

[placeholders]
"default" = { input = "Search applications...", list = "No applications found" }

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
left = ["Left"]
right = ["Right"]
down = ["Down"]
up = ["Up"]
toggle_exact = ["ctrl e"]
page_down = ["Page_Down"]
page_up = ["Page_Up"]

[providers]
default = ["desktopapplications"]
empty = ["desktopapplications"]
ignore_preview = []
max_results = 20

[providers.sets]
[providers.max_results_provider]

[providers.actions]
fallback = [
  { action = "menus:open", label = "open", after = "Nothing" },
  { action = "menus:default", label = "run", after = "Close" },
  { action = "menus:parent", label = "back", bind = "Escape", after = "Nothing" },
]

desktopapplications = [
  { action = "start", default = true, bind = "Return" },
  { action = "new_instance", label = "new instance", bind = "ctrl Return" },
]
