$primary = rgb(fe8019)
$secondary = rgb(fabd2f)
$background = rgb(282828)
$red = rgb(fb4934)
$green = rgb(b8bb26)
$yellow = rgb(fabd2f)
$blue = rgb(458588)
$orange = rgb(fe8019)
$purple = rgb(d3869b)
$aqua = rgb(8ec07c)