# --- PRELOAD DAS 5 IMAGENS ---
preload = /home/nathanmcunha/Pictures/Wallpapers/bird.png
preload = /home/nathanmcunha/Pictures/Wallpapers/cat-coffee.png
preload = /home/nathanmcunha/Pictures/Wallpapers/The_Backwater.png
preload = /home/nathanmcunha/Pictures/Wallpapers/Cat_at_Play.png
preload = /home/nathanmcunha/Pictures/Wallpapers/The_Artists_Garden_at_Eragny.png

# --- WALLPAPER INICIAL ---
# Define um deles para começar (no monitor HDMI-A-4)
wallpaper = HDMI-A-4,/home/nathanmcunha/Pictures/Wallpapers/The_Backwater.png

splash = false