general {
       lock_cmd = pidof hyprlock || hyprlock       # command to run when idle
       before_sleep_cmd = loginctl lock-session    # command to run before sleep
       after_sleep_cmd = hyprctl dispatch dpms on && ~/.config/hypr/scripts/qs_manager.sh restart  # command to run after wakeup
   }

   listener {
       timeout = 1300                                # 5 minutes
       on-timeout = loginctl lock-session           # lock screen when timeout has passed
   }

listener {
        timeout = 330                                # 5.5 minutes
        on-timeout = hyprctl dispatch dpms off       # turn off monitor
        on-resume = hyprctl dispatch dpms on && sleep 0.5 && ~/.config/hypr/scripts/qs_manager.sh restart  # turn on monitor + restart quickshell
    }