general {
       lock_cmd = noctalia-shell ipc call lockScreen lock       # command to run when idle
       before_sleep_cmd = loginctl lock-session    # command to run before sleep
       after_sleep_cmd = hyprctl dispatch dpms on
   }

   listener {
       timeout = 1300                                # 5 minutes
       on-timeout = noctalia-shell ipc call lockScreen lock           # lock screen when timeout has passed
   }

listener {
        timeout = 330                                # 5.5 minutes
        on-timeout = hyprctl dispatch dpms off       # turn off monitor
        on-resume = hyprctl dispatch dpms on
    }