[config]
reload_apps = true
mode = "light"
prefer = "saturation"
# --- WOFI ---
[templates.wofi]
input_path = "~/.config/matugen/templates/wofi-style.css"
output_path = "~/.config/wofi/style.css"

# --- HYPRLAND (Recarrega as bordas automaticamente) ---
[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

# --- QUICKSHELL (Dynamic colors for the bar and popups) ---
[templates.quickshell]
input_path = "~/.config/matugen/templates/qs-colors.json"
output_path = "/tmp/qs_colors.json"