;;; noctalia-colors.el --- Generated by noctalia -*- lexical-binding: t -*-
;; DO NOT EDIT - regenerated on wallpaper/theme change

(defvar nm/noctalia-colors
  '(;; Material 3 palette from wallpaper
    (bg . "{{colors.surface.default.hex}}")
    (fg . "{{colors.on_surface.default.hex}}")
    (bg-alt . "{{colors.surface_container.default.hex}}")
    (bg-alt2 . "{{colors.surface_container_high.default.hex}}")
    (fg-alt . "{{colors.on_surface_variant.default.hex}}")
    (primary . "{{colors.primary.default.hex}}")
    (secondary . "{{colors.secondary.default.hex}}")
    (tertiary . "{{colors.tertiary.default.hex}}")
    (error . "{{colors.error.default.hex}}")
    (outline . "{{colors.outline.default.hex}}")
    (outline-variant . "{{colors.outline_variant.default.hex}}")
    (surface-variant . "{{colors.surface_variant.default.hex}}")
    (primary-container . "{{colors.primary_container.default.hex}}")
    (secondary-container . "{{colors.secondary_container.default.hex}}")
    (tertiary-container . "{{colors.tertiary_container.default.hex}}"))
  "Noctalia Material 3 colors extracted from current wallpaper.")

(provide 'noctalia-colors)
;;; noctalia-colors.el ends here
