$primary = rgb({{colors.primary.default.hex_stripped}})
$secondary = rgb({{colors.secondary.default.hex_stripped}})
$background = rgb({{colors.surface.default.hex_stripped}})
$red = rgb({{colors.error.default.hex_stripped}})
$green = rgb({{colors.tertiary.default.hex_stripped}})
$yellow = rgb({{colors.secondary.default.hex_stripped}})
$blue = rgb({{colors.primary.default.hex_stripped}})
$orange = rgb({{colors.error_container.default.hex_stripped}})
$purple = rgb({{colors.tertiary.default.hex_stripped}})
$aqua = rgb({{colors.primary_fixed.default.hex_stripped}})
